@startuml
skinparam classAttributeIconSize 0
    class College {
        + btnSave : JButton
        + dob : JTextArea
        + gpa : JTextArea
        + name : JTextArea
        + studentRecords : ArrayList
        + tNumber : JTextArea
        ~ currentDetails : int
        ~ savedStudentDetails : int
        + College()
    }

    class College.ButtonListener {
        + actionPerformed()
}

    class Driver {
        {static} + main()

  }

    class StudentOriginator {
        + dob : String
        + gpa : Float
        + name : String
        + studentRecords : ArrayList
        + tNumber : String
        + StudentOriginator()
        + addStudent()
        + getDob()
        + getGpa()
        + getName()
        + getTNumber()
        + removeStudent()
        + setDob()
        + setGpa()
        + setName()
        + settNumber()
        + toString()
    }

  

  College -up-|> javax.swing.JFrame
  College +-down- College.ButtonListener
  College.ButtonListener .up.|> java.awt.event.ActionListener
  StudentOriginator -up-|> College



@enduml
