@startuml

skinparam classAttributeIconSize 0

class StudentOriginator {
+ tNumber: String
+ name: String
+ address: String
+ dob: String
+ gpa: Float
+ addStudent(): void
+ removeStudent(): void
+ toString(): String
}

class GUI{
savedStudents: ArrayList[]


}

class Driver{

}



@enduml